import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../../../widgets/appbar.dart';
import '../../../widgets/bottom_navbar.dart';
import '../../../core/constants/colors.dart';
import 'package:assignment/widgets/vehicle_add_card.dart';
import 'package:assignment/widgets/vehicle_info_card.dart';
import 'package:assignment/pages/home/home_empty_view.dart';