// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWPPeXmyJE17CEzlaYqjySG85-cbmrB6k',
    appId: '1:917618545128:web:4956f4fdb2554e57c8d45d',
    messagingSenderId: '917618545128',
    projectId: 'track-pit',
    authDomain: 'track-pit.firebaseapp.com',
    storageBucket: 'track-pit.firebasestorage.app',
    measurementId: 'G-DR81ZJCB3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQR3S5G5d8Q-lH-lJijtbHvfZLd9w4nGQ',
    appId: '1:917618545128:android:4dbb40af9b7795fac8d45d',
    messagingSenderId: '917618545128',
    projectId: 'track-pit',
    storageBucket: 'track-pit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Ld7lkGAzc2Vr2zxoBYcdLQlve_sfwis',
    appId: '1:917618545128:ios:c0ac67d254047dc3c8d45d',
    messagingSenderId: '917618545128',
    projectId: 'track-pit',
    storageBucket: 'track-pit.firebasestorage.app',
    iosBundleId: 'com.greenstem.trackPit',
  );
}
