// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAORigYkPsFHWIyziQUXad5BxroUbXCj3E',
    appId: '1:462040031000:web:d4cf05c7f715d47a8f086d',
    messagingSenderId: '462040031000',
    projectId: 'trackpit-701b7',
    authDomain: 'trackpit-701b7.firebaseapp.com',
    storageBucket: 'trackpit-701b7.firebasestorage.app',
    measurementId: 'G-N5V848T3HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAJ1noaG6bEE9WvoGjZcb7r1bwclduWEo',
    appId: '1:462040031000:android:9e3d3e725c815bb78f086d',
    messagingSenderId: '462040031000',
    projectId: 'trackpit-701b7',
    storageBucket: 'trackpit-701b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb-k4V4jf6LMtxVZwDENz1IeXj85x9tOk',
    appId: '1:462040031000:ios:6946b3e262e49d848f086d',
    messagingSenderId: '462040031000',
    projectId: 'trackpit-701b7',
    storageBucket: 'trackpit-701b7.firebasestorage.app',
    iosClientId: '462040031000-t6d3fv04d8e4t8dvb6kc212cdo9i1id3.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb-k4V4jf6LMtxVZwDENz1IeXj85x9tOk',
    appId: '1:462040031000:ios:6946b3e262e49d848f086d',
    messagingSenderId: '462040031000',
    projectId: 'trackpit-701b7',
    storageBucket: 'trackpit-701b7.firebasestorage.app',
    iosClientId: '462040031000-t6d3fv04d8e4t8dvb6kc212cdo9i1id3.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAORigYkPsFHWIyziQUXad5BxroUbXCj3E',
    appId: '1:462040031000:web:325e9d6753bcdb098f086d',
    messagingSenderId: '462040031000',
    projectId: 'trackpit-701b7',
    authDomain: 'trackpit-701b7.firebaseapp.com',
    storageBucket: 'trackpit-701b7.firebasestorage.app',
    measurementId: 'G-6JMY82SKX6',
  );
}
